general:
steps:
  gctsCloneRepository:
    host: 'http://slaa9114.btcdev.btc-ag.int:8000'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'matthiasatbtc-gcts3'
  gctsCreateRepository:
    host: 'http://slaa9114.btcdev.btc-ag.int:8000'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'matthiasatbtc-gcts3'
    remoteRepositoryURL: 'https://github.com/MatthiasATBTC/gCTS3'
    vSID: 'GTG'
